started d1s3
scta-texts/yth33t pull request #4
Opened 2024-12-19 18:30 UTC by justinshauncoyle

2024-12-23 21:08 UTC, justinshauncoyle commented
Finished draft of s3

2024-12-23 21:47 UTC, justinshauncoyle commented
Fixed issue with simple expressions

2025-01-10 18:26 UTC, jeffreycwitt requested changes

2025-01-10 18:26 UTC, jeffreycwitt commented on yth33t-f2x82/cod-hbbgut_yth33t-f2x82.xml
> +        <lb ed="#K"/>futura in Bethlehem, quam ibidem testatur <ref>Lucas 2<!-- actually Luke 2:1-7 --></ref>factam esse. <ref>Ieremiae 31</ref> praedi<lb ed="#K" break="no"/>cis
```suggestion
        <lb ed="#K"/>futura in Bethlehem, quam ibidem testatur <ref>Lucas 2<!-- actually Luke 2:1-7 --></ref> factam esse. <ref>Ieremiae 31</ref> praedi<lb ed="#K" break="no"/>cis
```

2025-01-10 18:27 UTC, merged